import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "sonner";
import Providers from "./components/ProgressBarProvider";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Raleway } from "next/font/google";

const raleway = Raleway({ 
  subsets: ["latin"], 
  weight: ["400", "700"], // Add desired weights
  variable: "--font-raleway" // Optional: Use CSS variable
});
export const metadata: Metadata = {
  title: "Badminton",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`${raleway.variable}`}>
        <SessionProvider session={session}>
          <Providers>
          <Toaster richColors />
          <AppRouterCacheProvider>
            {children}
          </AppRouterCacheProvider>
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
    